"""
Django settings for blog_project project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-+4v_n9(cav)1x8l$xt-3-#!54h!5-n&ngtn=@i@zx*l=-9$%_6"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "blog",
    "czauth",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "blog_project.urls"

# 模版配置
TEMPLATES = [
    {
        # 指定使用 Django 自带的模板引擎
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        # 设置模板文件目录，这里指向项目根目录下的 templates 文件夹
        "DIRS": [os.path.join(BASE_DIR, 'templates')],
        # 允许 Django 在每个已安装的 app 中查找 templates 目录
        "APP_DIRS": True,
        # 模板引擎的额外选项
        "OPTIONS": {
            # 上下文处理器列表，用于向模板添加常用变量
            "context_processors": [
                # 添加 debug 变量
                "django.template.context_processors.debug",
                # 添加request对象
                "django.template.context_processors.request",
                # 添加用户认证信息
                "django.contrib.auth.context_processors.auth",    #判断用户状态，是否登录成功
                # 添加消息框架功能
                "django.contrib.messages.context_processors.messages",
            ],
            # 这里加载静态文件
            'builtins': ['django.templatetags.static']
        },
    },
]

WSGI_APPLICATION = "blog_project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "OPTIONS": {
            "read_default_file": 'my.cnf',  # 配置数据库文件
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",},
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"
# 静态文件加载路径
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# 在qq邮箱-设置-账号-POP3/IMAP/SMTP/Exchange/CardDAV/CalDAV服务-开启服务
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.qq.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = '1170860535@qq.com'
EMAIL_HOST_PASSWORD = 'bwvjwwmaylsbheih'   # 服务的授权码
DEFAULT_FROM_EMAIL = '1170860535@qq.com'
